name: bubbles
description: "Bubbles"
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flame: ^1.19.0
  flame_forge2d: ^0.18.2
  forge2d: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/interests.json
